// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdCaKAE0D-1S1VlWP_5WMPK_YWpQas3OI',
    appId: '1:658269086140:web:5cfd21213607e67edf8bb9',
    messagingSenderId: '658269086140',
    projectId: 'busapp-8cf39',
    authDomain: 'busapp-8cf39.firebaseapp.com',
    storageBucket: 'busapp-8cf39.appspot.com',
    measurementId: 'G-QC85Z9T93R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcmfpYEjnNQOehbXsDyK72uTPR3uBKXzg',
    appId: '1:658269086140:android:3975229c1c845d14df8bb9',
    messagingSenderId: '658269086140',
    projectId: 'busapp-8cf39',
    storageBucket: 'busapp-8cf39.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAjSC4P-XCrepQQgfrRJqkwWrBLs2kYSc',
    appId: '1:658269086140:ios:f5acdbba6afadf94df8bb9',
    messagingSenderId: '658269086140',
    projectId: 'busapp-8cf39',
    storageBucket: 'busapp-8cf39.appspot.com',
    iosBundleId: 'com.example.busCompanion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAjSC4P-XCrepQQgfrRJqkwWrBLs2kYSc',
    appId: '1:658269086140:ios:f5acdbba6afadf94df8bb9',
    messagingSenderId: '658269086140',
    projectId: 'busapp-8cf39',
    storageBucket: 'busapp-8cf39.appspot.com',
    iosBundleId: 'com.example.busCompanion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdCaKAE0D-1S1VlWP_5WMPK_YWpQas3OI',
    appId: '1:658269086140:web:cf2fa59f54913474df8bb9',
    messagingSenderId: '658269086140',
    projectId: 'busapp-8cf39',
    authDomain: 'busapp-8cf39.firebaseapp.com',
    storageBucket: 'busapp-8cf39.appspot.com',
    measurementId: 'G-H0VGREE8TC',
  );
}
